### [ 생성 무게 예측 회귀 모델 구현 ]

- 데이터 관련 
    * 로딩 및 기본 확인 : EDA
    * 전처리 진행
    * 데이터 가공 (통계치 X) : 불필요 커럼 제거

- 학습 관련
    * 피쳐, 타겟 분리
    * 데이터셋 분리 : 학습용/검증용/테스트용
    * 학습용 데이터셋으로 가공 -> 데이터 누수 예방
    * 학습/검증/테스트 함수 

- 학습 진행
    * 학습 관련 설정값 <= 하이퍼파라미터들
    * 학습 관련 인스턴스들
    * 학습 진행 + 진행 과정에 대한 로그 : 학습과 검증의 loss, score 등등 
    
- 학습 평가
    * 학습 과정 로그기반 시각화 
    * 과대/과소/최적 평가

>> **[1] 데이터 준비 및 확인**

In [1]:
## --------------------------------------------------
## 모듈 로딩
## --------------------------------------------------
## 데이터 관련
import pandas as pd 
import numpy as np

In [2]:
## --------------------------------------------------
## 데이터 선정 및 로딩
## --------------------------------------------------
## => 첫번째 줄 컬럼명 OK, 첫번째 컬럼 불필요 
fishDF = pd.read_csv('../../[8] 머신러닝/Data/Numbers/fish.csv', usecols=[1,2,3,4,5])

In [3]:
## --------------------------------------------------
## 데이터 기본 정보 확인 : 실제 데이터와 타입 체크 
## --------------------------------------------------
display(fishDF.head(2))
fishDF.info()

   Weight  Length  Diagonal  Height   Width
0   242.0    25.4      30.0   11.52  4.0200
1   290.0    26.3      31.2   12.48  4.3056

<class 'pandas.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Weight    159 non-null    float64
 1   Length    159 non-null    float64
 2   Diagonal  159 non-null    float64
 3   Height    159 non-null    float64
 4   Width     159 non-null    float64
dtypes: float64(5)
memory usage: 6.3 KB

In [4]:
## --------------------------------------------------
## 컬럼별 값의 범위 확인 : 기술통계 확인
## --------------------------------------------------
fishDF.describe()

## [체크] --------------------------------------------
## 피쳐별 값의 범위 차이가 있음 => 스케일링 필요
## 타겟 컬럼 Weight의 최소값 0 => 결측치인데 0으로 채워진듯
##                             몇개 존재하는지 체크 필요
## --------------------------------------------------

            Weight      Length    Diagonal      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   28.415723   31.227044    8.970994    4.417486
std     357.978317   10.716328   11.610246    4.286208    1.685804
min       0.000000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   63.400000   68.000000   18.957000    8.142000

In [5]:
## -------------------------------------------
## 타겟 컬럼 Weight가 0인 행 즉, 샘플 개수 체크
## -------------------------------------------
zero_cnt = (fishDF['Weight'] == 0).sum()
zero_idx = fishDF[fishDF['Weight'] == 0].index.to_list()

print(f'무게가 0인 데이터 개수 : {zero_cnt}개, 행인덱스 번호 : {zero_idx}')

무게가 0인 데이터 개수 : 1개, 행인덱스 번호 : [40]

In [6]:
## 삭제 진행
cleanDF = fishDF.drop(index=zero_idx)
cleanDF.reset_index(drop=True, inplace=True)

In [7]:
## 확인 진행
cleanDF.head(), cleanDF.tail(), (cleanDF['Weight']==0).sum()

(   Weight  Length  Diagonal   Height   Width
 0   242.0    25.4      30.0  11.5200  4.0200
 1   290.0    26.3      31.2  12.4800  4.3056
 2   340.0    26.5      31.1  12.3778  4.6961
 3   363.0    29.0      33.5  12.7300  4.4555
 4   430.0    29.0      34.0  12.4440  5.1340,
      Weight  Length  Diagonal  Height   Width
 153    12.2    12.2      13.4  2.0904  1.3936
 154    13.4    12.4      13.5  2.4300  1.2690
 155    12.2    13.0      13.8  2.2770  1.2558
 156    19.7    14.3      15.2  2.8728  2.0672
 157    19.9    15.0      16.2  2.9322  1.8792,
 np.int64(0))

In [8]:
## 무게 0인 행 제거 후 다시 분포확인
cleanDF.describe()

## [확인] ----------------------------------------
## 타겟 Weight 컬럼의 값의 분포 : 넓게 퍼져있음. 
##                             최소-최대 차이 큼
##                             오른쪽으로 치우쳐 있음
## -----------------------------------------------

            Weight      Length    Diagonal      Height       Width
count   158.000000  158.000000  158.000000  158.000000  158.000000
mean    400.847468   28.465823   31.280380    8.986790    4.424232
std     357.697796   10.731707   11.627605    4.295191    1.689010
min       5.900000    8.400000    8.800000    1.728400    1.047600
25%     121.250000   21.000000   23.200000    5.940600    3.398650
50%     281.500000   27.400000   29.700000    7.789000    4.277050
75%     650.000000   35.750000   39.675000   12.371850    5.586750
max    1650.000000   63.400000   68.000000   18.957000    8.142000

>> **[2] 학습 데이터 준비**

In [9]:
## -----------------------------------------
## 모듈로딩
## -----------------------------------------
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

In [10]:
## -----------------------------------------
## [2-1] 피쳐와 타겟 분리
## -----------------------------------------
featureDF = cleanDF[cleanDF.columns[1:]]
targetSR  = cleanDF[cleanDF.columns[0]]

print(f'featureDF : {featureDF.shape} targetSR : {targetSR.shape}')

featureDF : (158, 4) targetSR : (158,)

In [11]:
## ----------------------------------------------
## [2-2] 타겟 컬럼 스케일링여부 결정
## ----------------------------------------------
targetSR.describe()

## [결정] ---------------------------------------
## - 값들의 범위가 넓게 퍼짐 즉, 값의 차이 큼!!
## - 오른쪽으로 즉, 큰 무게에 해당하는 데이터가 더 많음
## - 타겟도 스케일링 필요함
## - 값의 차이 크기 때문에 학습용 기준 스케일링 진행
## - 검증용/테스트용에 적용
## ----------------------------------------------

count     158.000000
mean      400.847468
std       357.697796
min         5.900000
25%       121.250000
50%       281.500000
75%       650.000000
max      1650.000000
Name: Weight, dtype: float64

In [12]:
## -----------------------------------------
## [2-3] 데이터셋 분리 : 학습용 | 검증용 | 테스트용
## -----------------------------------------
## => 학습용 : 테스트용 = 8 :2
X_train, X_test, Y_train, Y_test = train_test_split(featureDF,
                                                    targetSR,
                                                    test_size=0.2,
                                                    random_state=12)

## => 학습용 : 검증용   = 8 :2
X_train, X_valid, Y_train, Y_valid = train_test_split(  X_train,
                                                        Y_train,
                                                        test_size=0.2,
                                                        random_state=12)

In [13]:
## 데이터셋 확인
print(f'[TRAIN] {X_train.shape},  {Y_train.shape}')
print(f'[VALID] {X_valid.shape},  {Y_valid.shape}')
print(f'[TEST ] {X_test.shape},   {Y_test.shape}')

[TRAIN] (100, 4),  (100,)
[VALID] (26, 4),  (26,)
[TEST ] (32, 4),   (32,)

In [14]:
## -----------------------------------------
## [2-4] 학습용 기준 타겟 스케일링 : 데이터 누수
## - 딥러닝 학습 시 권장 사항
##   *안정적인 학습/자연스러운 기울기 업데이트 등의 이유로
##    평균0, 표준편차1이 되는 데이터를 좋아함
## -----------------------------------------
targetScaler = StandardScaler()

## 학습용 : SR -> DF : to_frame()
scY_train = targetScaler.fit_transform(Y_train.to_frame())

## 검증용, 테스트용 
scY_test  = targetScaler.transform(Y_test.to_frame())
scY_valid = targetScaler.transform(Y_valid.to_frame())

In [15]:
## 타겟 스케일링 후 확인
print(f'[TRAIN] {scY_train.shape},  {scY_train.dtype},  {scY_train.ndim}D')
print(f'[VALID] {scY_valid.shape},  {scY_valid.dtype},  {scY_valid.ndim}D')
print(f'[TEST ] {scY_test.shape},  {scY_test.dtype},  {scY_test.ndim}D')

[TRAIN] (100, 1),  float64,  2D
[VALID] (26, 1),  float64,  2D
[TEST ] (32, 1),  float64,  2D

In [16]:
## -----------------------------------------
## [2-5] 피쳐 스케일링 : By 학습용 스케일러
## -----------------------------------------
featureScaler = StandardScaler()

## 학습용 기준 스케일러 생성
scX_train = featureScaler.fit_transform(X_train)

## 검증용, 테스트용 
scX_test  = featureScaler.transform(X_test)
scX_valid = featureScaler.transform(X_valid)

In [17]:
## 타겟 스케일링 후 확인
print(f'[TRAIN] {scX_train.shape},  {scX_train.dtype},  {scX_train.ndim}D')
print(f'[VALID] {scX_valid.shape},  {scX_valid.dtype},  {scX_valid.ndim}D')
print(f'[TEST ] {scX_test.shape},  {scX_test.dtype},  {scX_test.ndim}D')

[TRAIN] (100, 4),  float64,  2D
[VALID] (26, 4),  float64,  2D
[TEST ] (32, 4),  float64,  2D

>> **[3] 학습 준비**

In [18]:
## -----------------------------------------
## 모듈로딩
## -----------------------------------------
## 학습관련 모듈들
import torch
from torch.nn import MSELoss                ## 손실함수    클래스
from torch.optim import Adam                ## 최적화     클래스
from torch.utils.data import DataLoader     ## 데이터로더  클래스

## 성능지표 관련 모듈
from sklearn.metrics import mean_squared_error, r2_score

## 사용자 정의 클래스 및 학습관련 함수 모듈
import sys
sys.path.append(r'D:\KDT\VS_KDT_14\[9]_DL\DAY05')
from dnn_fish_class import *
from reg_func import *

In [19]:
## ----------------------------------------------------------
## 학습 진행 관련 설정들
## ----------------------------------------------------------
## => 처음~끝까지 학습 횟수
EPOCHS = 50

## => 학습량 크기
BS = 25

## => W,B 업데이트/값 보정 간격
LR = 0.001

## => 학습 위치 
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'DEVICE => {DEVICE}')

DEVICE => cuda

In [20]:
## ----------------------------------------------------------
## 인스턴스 생성
## ----------------------------------------------------------
## => 모델 인스턴스 생성 + 저장 위치 설정
model = WeightRegression().to(DEVICE)

## => 최적화 인스턴스
adamOP = Adam(model.parameters(), lr=LR)

## => 손실함수 인스턴스 : 회귀용
lossFN = MSELoss()

## => 데이터로더 인스턴스
## => train : valid : test = 100 : 26 : 32
trainDL = DataLoader( WeightDataset(scX_train, scY_train), batch_size=BS, shuffle=True )
validDL = DataLoader( WeightDataset(scX_valid, scY_valid), batch_size=len(scX_valid) )
testDL  = DataLoader( WeightDataset(scX_test,  scY_test),  batch_size=len(scX_test) )

>> **[4] 학습 진행**

In [21]:
## ----------------------------------------------------------
## 학습 진행
## ----------------------------------------------------------
## 에포크 단위 손실과 정확도 저장 변수
epochHist = {'T_LOSS':[], 'T_R2':[], 'T_RMSE':[], 'V_LOSS':[],  'V_R2':[], 'V_RMSE':[]}

## 에포크 단위 학습/검증 진행 
for epo in range(EPOCHS):
    ## 학습
    t_loss, t_mse, t_rmse, t_r2 = training_regression( model, trainDL, 
                                                       lossFN, adamOP, DEVICE)
    ## 검증
    v_loss, v_mse, v_rmse, v_r2 = evaluating_regression( model, validDL, 
                                                         lossFN, DEVICE )
    
    ## 학습 및 검증 로그 저장 
    for key, value in zip(epochHist.keys(), [t_loss, t_r2, t_rmse, v_loss, v_r2, v_rmse]):
        epochHist[key].append(value)

    print(f"[EPOCH -{epo:03}]", end=' ')
    print(f"TRAIN  => LOSS : {t_loss:.6f},   MSE : {t_mse:.6f},   RMSE : {t_rmse:.6f},   R2 : {t_r2:.6f}", end=' ')
    print(f'VALID  => LOSS : {v_loss:.6f},   MSE : {v_mse:.6f},   RMSE : {v_rmse:.6f},   R2 : {v_r2:.6f}')

[EPOCH -000] TRAIN  => LOSS : 32.381099,   MSE : 1.295244,   RMSE : 1.138088,   R2 : -0.295244 VALID  => LOSS : 32.440934,   MSE : 1.247728,   RMSE : 1.117018,   R2 : -0.861161
[EPOCH -001] TRAIN  => LOSS : 31.790731,   MSE : 1.271629,   RMSE : 1.127665,   R2 : -0.271629 VALID  => LOSS : 31.412366,   MSE : 1.208168,   RMSE : 1.099167,   R2 : -0.802152
[EPOCH -002] TRAIN  => LOSS : 31.320824,   MSE : 1.252833,   RMSE : 1.119300,   R2 : -0.252833 VALID  => LOSS : 30.369590,   MSE : 1.168061,   RMSE : 1.080769,   R2 : -0.742327
[EPOCH -003] TRAIN  => LOSS : 30.773702,   MSE : 1.230948,   RMSE : 1.109481,   R2 : -0.230948 VALID  => LOSS : 29.367717,   MSE : 1.129528,   RMSE : 1.062792,   R2 : -0.684848
[EPOCH -004] TRAIN  => LOSS : 30.266763,   MSE : 1.210671,   RMSE : 1.100305,   R2 : -0.210671 VALID  => LOSS : 28.395524,   MSE : 1.092136,   RMSE : 1.045053,   R2 : -0.629073
[EPOCH -005] TRAIN  => LOSS : 29.732065,   MSE : 1.189283,   RMSE : 1.090542,   R2 : -0.189283 VALID  => LOSS : 27.469985,   MSE : 1.056538,   RMSE : 1.027880,   R2 : -0.575974
[EPOCH -006] TRAIN  => LOSS : 29.295465,   MSE : 1.171818,   RMSE : 1.082506,   R2 : -0.171818 VALID  => LOSS : 26.537102,   MSE : 1.020658,   RMSE : 1.010276,   R2 : -0.522454
[EPOCH -007] TRAIN  => LOSS : 28.795028,   MSE : 1.151801,   RMSE : 1.073220,   R2 : -0.151801 VALID  => LOSS : 25.647361,   MSE : 0.986437,   RMSE : 0.993195,   R2 : -0.471409
[EPOCH -008] TRAIN  => LOSS : 28.306672,   MSE : 1.132267,   RMSE : 1.064080,   R2 : -0.132267 VALID  => LOSS : 24.799653,   MSE : 0.953833,   RMSE : 0.976644,   R2 : -0.422775
[EPOCH -009] TRAIN  => LOSS : 27.819105,   MSE : 1.112764,   RMSE : 1.054876,   R2 : -0.112764 VALID  => LOSS : 24.003678,   MSE : 0.923218,   RMSE : 0.960843,   R2 : -0.377109
[EPOCH -010] TRAIN  => LOSS : 27.364354,   MSE : 1.094574,   RMSE : 1.046219,   R2 : -0.094574 VALID  => LOSS : 23.218022,   MSE : 0.893001,   RMSE : 0.944987,   R2 : -0.332036
[EPOCH -011] TRAIN  => LOSS : 26.878675,   MSE : 1.075147,   RMSE : 1.036893,   R2 : -0.075147 VALID  => LOSS : 22.470776,   MSE : 0.864261,   RMSE : 0.929656,   R2 : -0.289166
[EPOCH -012] TRAIN  => LOSS : 26.441453,   MSE : 1.057658,   RMSE : 1.028425,   R2 : -0.057658 VALID  => LOSS : 21.724894,   MSE : 0.835573,   RMSE : 0.914097,   R2 : -0.246374
[EPOCH -013] TRAIN  => LOSS : 25.978278,   MSE : 1.039131,   RMSE : 1.019378,   R2 : -0.039131 VALID  => LOSS : 20.980022,   MSE : 0.806924,   RMSE : 0.898289,   R2 : -0.203640
[EPOCH -014] TRAIN  => LOSS : 25.531964,   MSE : 1.021279,   RMSE : 1.010583,   R2 : -0.021279 VALID  => LOSS : 20.254299,   MSE : 0.779011,   RMSE : 0.882616,   R2 : -0.162004
[EPOCH -015] TRAIN  => LOSS : 25.045838,   MSE : 1.001834,   RMSE : 1.000916,   R2 : -0.001834 VALID  => LOSS : 19.561749,   MSE : 0.752375,   RMSE : 0.867395,   R2 : -0.122272
[EPOCH -016] TRAIN  => LOSS : 24.588979,   MSE : 0.983559,   RMSE : 0.991746,   R2 : 0.016441 VALID  => LOSS : 18.904114,   MSE : 0.727081,   RMSE : 0.852691,   R2 : -0.084544
[EPOCH -017] TRAIN  => LOSS : 24.072455,   MSE : 0.962898,   RMSE : 0.981274,   R2 : 0.037102 VALID  => LOSS : 18.286206,   MSE : 0.703316,   RMSE : 0.838639,   R2 : -0.049094
[EPOCH -018] TRAIN  => LOSS : 23.610086,   MSE : 0.944403,   RMSE : 0.971804,   R2 : 0.055597 VALID  => LOSS : 17.672360,   MSE : 0.679706,   RMSE : 0.824443,   R2 : -0.013877
[EPOCH -019] TRAIN  => LOSS : 23.156660,   MSE : 0.926266,   RMSE : 0.962427,   R2 : 0.073734 VALID  => LOSS : 17.076054,   MSE : 0.656771,   RMSE : 0.810414,   R2 : 0.020334
[EPOCH -020] TRAIN  => LOSS : 22.691954,   MSE : 0.907678,   RMSE : 0.952721,   R2 : 0.092322 VALID  => LOSS : 16.506550,   MSE : 0.634867,   RMSE : 0.796786,   R2 : 0.053007
[EPOCH -021] TRAIN  => LOSS : 22.271477,   MSE : 0.890859,   RMSE : 0.943853,   R2 : 0.109141 VALID  => LOSS : 15.956156,   MSE : 0.613698,   RMSE : 0.783389,   R2 : 0.084583
[EPOCH -022] TRAIN  => LOSS : 21.876239,   MSE : 0.875050,   RMSE : 0.935441,   R2 : 0.124951 VALID  => LOSS : 15.426317,   MSE : 0.593320,   RMSE : 0.770273,   R2 : 0.114980
[EPOCH -023] TRAIN  => LOSS : 21.447859,   MSE : 0.857914,   RMSE : 0.926237,   R2 : 0.142086 VALID  => LOSS : 14.935716,   MSE : 0.574451,   RMSE : 0.757925,   R2 : 0.143127
[EPOCH -024] TRAIN  => LOSS : 21.075018,   MSE : 0.843001,   RMSE : 0.918151,   R2 : 0.156999 VALID  => LOSS : 14.456939,   MSE : 0.556036,   RMSE : 0.745678,   R2 : 0.170594
[EPOCH -025] TRAIN  => LOSS : 20.658313,   MSE : 0.826333,   RMSE : 0.909028,   R2 : 0.173667 VALID  => LOSS : 14.033998,   MSE : 0.539769,   RMSE : 0.734690,   R2 : 0.194859
[EPOCH -026] TRAIN  => LOSS : 20.329218,   MSE : 0.813169,   RMSE : 0.901759,   R2 : 0.186831 VALID  => LOSS : 13.649379,   MSE : 0.524976,   RMSE : 0.724552,   R2 : 0.216925
[EPOCH -027] TRAIN  => LOSS : 19.990147,   MSE : 0.799606,   RMSE : 0.894207,   R2 : 0.200394 VALID  => LOSS : 13.331329,   MSE : 0.512743,   RMSE : 0.716061,   R2 : 0.235171
[EPOCH -028] TRAIN  => LOSS : 19.678493,   MSE : 0.787140,   RMSE : 0.887209,   R2 : 0.212860 VALID  => LOSS : 13.046206,   MSE : 0.501777,   RMSE : 0.708362,   R2 : 0.251529
[EPOCH -029] TRAIN  => LOSS : 19.354866,   MSE : 0.774195,   RMSE : 0.879883,   R2 : 0.225805 VALID  => LOSS : 12.767247,   MSE : 0.491048,   RMSE : 0.700748,   R2 : 0.267533
[EPOCH -030] TRAIN  => LOSS : 19.069406,   MSE : 0.762776,   RMSE : 0.873371,   R2 : 0.237224 VALID  => LOSS : 12.489324,   MSE : 0.480359,   RMSE : 0.693079,   R2 : 0.283478
[EPOCH -031] TRAIN  => LOSS : 18.778335,   MSE : 0.751133,   RMSE : 0.866680,   R2 : 0.248867 VALID  => LOSS : 12.188158,   MSE : 0.468775,   RMSE : 0.684672,   R2 : 0.300756
[EPOCH -032] TRAIN  => LOSS : 18.486637,   MSE : 0.739465,   RMSE : 0.859922,   R2 : 0.260535 VALID  => LOSS : 11.898709,   MSE : 0.457643,   RMSE : 0.676493,   R2 : 0.317362
[EPOCH -033] TRAIN  => LOSS : 18.208765,   MSE : 0.728351,   RMSE : 0.853435,   R2 : 0.271649 VALID  => LOSS : 11.599378,   MSE : 0.446130,   RMSE : 0.667930,   R2 : 0.334535
[EPOCH -034] TRAIN  => LOSS : 17.885643,   MSE : 0.715426,   RMSE : 0.845828,   R2 : 0.284574 VALID  => LOSS : 11.290785,   MSE : 0.434261,   RMSE : 0.658985,   R2 : 0.352239
[EPOCH -035] TRAIN  => LOSS : 17.558133,   MSE : 0.702325,   RMSE : 0.838049,   R2 : 0.297675 VALID  => LOSS : 10.991588,   MSE : 0.422753,   RMSE : 0.650195,   R2 : 0.369404
[EPOCH -036] TRAIN  => LOSS : 17.221397,   MSE : 0.688856,   RMSE : 0.829973,   R2 : 0.311144 VALID  => LOSS : 10.686382,   MSE : 0.411015,   RMSE : 0.641104,   R2 : 0.386914
[EPOCH -037] TRAIN  => LOSS : 16.895994,   MSE : 0.675840,   RMSE : 0.822095,   R2 : 0.324160 VALID  => LOSS : 10.381892,   MSE : 0.399304,   RMSE : 0.631905,   R2 : 0.404383
[EPOCH -038] TRAIN  => LOSS : 16.546741,   MSE : 0.661870,   RMSE : 0.813554,   R2 : 0.338130 VALID  => LOSS : 10.073961,   MSE : 0.387460,   RMSE : 0.622463,   R2 : 0.422049
[EPOCH -039] TRAIN  => LOSS : 16.184319,   MSE : 0.647373,   RMSE : 0.804595,   R2 : 0.352627 VALID  => LOSS : 9.769437,   MSE : 0.375748,   RMSE : 0.612982,   R2 : 0.439520
[EPOCH -040] TRAIN  => LOSS : 15.834782,   MSE : 0.633391,   RMSE : 0.795859,   R2 : 0.366609 VALID  => LOSS : 9.461869,   MSE : 0.363918,   RMSE : 0.603256,   R2 : 0.457165
[EPOCH -041] TRAIN  => LOSS : 15.478138,   MSE : 0.619126,   RMSE : 0.786845,   R2 : 0.380874 VALID  => LOSS : 9.164274,   MSE : 0.352472,   RMSE : 0.593694,   R2 : 0.474239
[EPOCH -042] TRAIN  => LOSS : 15.132282,   MSE : 0.605291,   RMSE : 0.778005,   R2 : 0.394709 VALID  => LOSS : 8.865674,   MSE : 0.340987,   RMSE : 0.583941,   R2 : 0.491369
[EPOCH -043] TRAIN  => LOSS : 14.805990,   MSE : 0.592240,   RMSE : 0.769571,   R2 : 0.407760 VALID  => LOSS : 8.570166,   MSE : 0.329622,   RMSE : 0.574127,   R2 : 0.508323
[EPOCH -044] TRAIN  => LOSS : 14.457529,   MSE : 0.578301,   RMSE : 0.760461,   R2 : 0.421699 VALID  => LOSS : 8.282898,   MSE : 0.318573,   RMSE : 0.564423,   R2 : 0.524804
[EPOCH -045] TRAIN  => LOSS : 14.132891,   MSE : 0.565316,   RMSE : 0.751875,   R2 : 0.434684 VALID  => LOSS : 7.999260,   MSE : 0.307664,   RMSE : 0.554675,   R2 : 0.541076
[EPOCH -046] TRAIN  => LOSS : 13.760434,   MSE : 0.550417,   RMSE : 0.741901,   R2 : 0.449583 VALID  => LOSS : 7.722525,   MSE : 0.297020,   RMSE : 0.544996,   R2 : 0.556953
[EPOCH -047] TRAIN  => LOSS : 13.436602,   MSE : 0.537464,   RMSE : 0.733119,   R2 : 0.462536 VALID  => LOSS : 7.446101,   MSE : 0.286389,   RMSE : 0.535153,   R2 : 0.572811
[EPOCH -048] TRAIN  => LOSS : 13.091274,   MSE : 0.523651,   RMSE : 0.723637,   R2 : 0.476349 VALID  => LOSS : 7.182269,   MSE : 0.276241,   RMSE : 0.525586,   R2 : 0.587948
[EPOCH -049] TRAIN  => LOSS : 12.772102,   MSE : 0.510884,   RMSE : 0.714762,   R2 : 0.489116 VALID  => LOSS : 6.927011,   MSE : 0.266423,   RMSE : 0.516162,   R2 : 0.602592

>> **[5] 학습평가**

In [22]:
## --------------------------------------------------
## 학습과 검증 비교 시각화
## --------------------------------------------------

In [23]:
## --------------------------------------------------
## 테스트
## --------------------------------------------------
loss, mse, rmse, r2 = evaluating_regression( model, testDL, lossFN, DEVICE )

print(f'TEST 데이터셋에 대한 성능평가')
print(f'- Loss : {loss:.6f}\n- R2   : {r2:.6f}')
print(f'- MSE  : {mse:.6f}\n- RMSE : {rmse:.6f}')

TEST 데이터셋에 대한 성능평가
- Loss : 16.360245
- R2   : 0.528462
- MSE  : 0.511258
- RMSE : 0.715023

>> **[6] 모델 또는 파라미터 저장 & 부가적인 기능들 저장**

In [24]:
## -------------------------------------------
## [6-1] 모델 저장 경로 설정 및 파일명 
## -------------------------------------------
## 모듈 로딩
import os 

## 모델 저장 폴더
MODEL_DIR = '../Models'

## 모델 파일명
PARAMS_FILE = 'fish_model_weights.pth'     ## 층별 파라미터(W, b) 만 저장 
ALL_FILE    = 'fish_model_all.pt'          ## 모델 구조 + 층별 파라미터(W, b) 모두 저장

In [25]:
## 모델 폴더 체크 
os.makedirs(MODEL_DIR, exist_ok=True) 


## (1) 층별 파라미터(W, b) 만 저장 
torch.save(model.state_dict() , f'{MODEL_DIR}/{PARAMS_FILE}')


## (2) 모델 구조 +  층별 파라미터(W, b) 저장 
torch.save(model , f'{MODEL_DIR}/{ALL_FILE}')

In [26]:
## -------------------------------------------
## [6-2] 부가 기능 및 데이터 저장 
## -------------------------------------------
## 모듈 로딩
import joblib

## 저장 폴더
MODEL_DIR = '../Models'

## 전처리기 : 스케일러 2개
F_SCALER = 'featureScaler.pkl'      ## 입력 피쳐용 스케일러
T_SCALER = 'targetScaler.pkl'       ## 타겟용 스케일러

## 부가데이터 
F_COLS  =  'featureColos.pkl'       ## 입력 피쳐의 컬럼명

In [27]:
## => 전처리기 : 스케일러 2개 저장
joblib.dump(featureScaler,  f'{MODEL_DIR}/{F_SCALER}')
joblib.dump(targetScaler,   f'{MODEL_DIR}/{T_SCALER}')

['../Models/targetScaler.pkl']

In [28]:
## => 부가데이터: 입력 피쳐의 컬럼명 저장 
joblib.dump(featureDF.columns.to_list(),  f'{MODEL_DIR}/{F_COLS}')

['../Models/featureColos.pkl']

>> **[7]예측**

In [29]:
## -------------------------------------------------------
## 새로운 생선의 무게 예측 
## -------------------------------------------------------
## -> 입력 : DataFrame으로 저장(DataFrame) -> 피쳐 스케일링(ndarray) -> Tensor화
## -> 출력 : Tensor -> 타겟 스케일로 복원된 2D 
## -------------------------------------------------------

## 정답 Weight = 242인 데이터라고 가정
## 피쳐 : Length, Diagonal, Height, Width
new_data = pd.DataFrame( [[25.4, 30, 11.52, 4.02]], columns=featureDF.columns )

## 학습용 데이터셋기반 피쳐 스케일러 사용 
scaled_data = featureScaler.transform(new_data)

## Tensor 변환
data = torch.tensor(scaled_data, dtype=torch.float32)

## 예측 : 타겟 스케일러로 복원된 예측값 반환
pred_weight = predict_regression( data, model, targetScaler, DEVICE)

print(f'예측 무게 : {pred_weight[0][0]}')

예측 무게 : 431.598876953125

In [30]:
## ----------------------------------------------------------
## [2] 저장된 모델 로딩해서 예측하기 : torch.load(모델파일)
## ----------------------------------------------------------
loadAModel =  torch.load(f'{MODEL_DIR}/{ALL_FILE}', weights_only=False)

## 예측 : 타겟 스케일러로 복원된 예측값 반환
pred_weight = predict_regression( data, loadAModel, targetScaler, DEVICE)

print(f'예측 무게 : {pred_weight[0][0]}')

예측 무게 : 431.598876953125

In [31]:
## ----------------------------------------------------------
## [3] 저장된 모델 파라미터 로딩해서 예측하기 : torch.load(모델파일)
## ----------------------------------------------------------
## 층별 가중치와 절편값만 존재
paramModel =  torch.load(f'{MODEL_DIR}/{PARAMS_FILE}', weights_only=True)

## 모델의 층별 가중치와 절편값으로 로딩
newModel = WeightRegression().to(DEVICE)           ## 모든 층의 가중치와 절편 초기화 
newModel.load_state_dict(paramModel)               ## 학습 완료 후 저장된 가중치와 절편 로딩

## 예측 : 타겟 스케일러로 복원된 예측값 반환
pred_weight = predict_regression( data, newModel, targetScaler, DEVICE)

print(f'예측 무게 : {pred_weight[0][0]}')

예측 무게 : 431.598876953125