### 데이터프레임 합치기
- 연결
    - 구성 형태와 속성 균일
    - 행 또는 열 중에 한 방향으로 단순 이어 붙이는 것
    - 일관성 유지
```python
pandas.concat([ DF1, … , DFn] ,
    axis=0, # 행 방향
    ignore_index=False, # 행 인덱스 유지
    join='outer', # 열 이름 합집합
    keys=[] # 행/열 이름 재정의
)

``` py
result1 = pd.concat( [df1, df2] )
# 행 방향 , 인덱스 유지, 열이름 합집합

result1 = pd.concat( [df1, df2], join= ‘inner’ )
행 방향 , 인덱스 유지, 열이름 교집합

result1 = pd.concat( [df1, df2], ignore_index=True )
행 방향 , 인덱스 변경, 합집합

result1 = pd.concat( [df1, df2], key=[ ‘A’, ’B’] )
행 방향 , 멀티인덱스, 합집합

result1 = pd.concat( [df1, df2], axis='columns‘ )
열/컬럼 방향 , 기존 인덱스 유지, 행인덱스 합집합
```

In [1]:
import pandas as pd
df1 = pd.DataFrame({'a':['a0','a1','a2','a3'],
                    'b':['b0','b1','b2','b3'],
                    'c':['c0','c1','c2','c3']},
                    index=[0,1,2,3])
df1

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3

In [2]:
df2 = pd.DataFrame({'a':['a2','a3','a4','a5'],
                    'b':['b2','b3','b4','b5'],
                    'c':['c2','c3','c4','c5'],
                    'd':['d2','d3','d4','d5']},
                    index=[2,3,4,5])
df2

    a   b   c   d
2  a2  b2  c2  d2
3  a3  b3  c3  d3
4  a4  b4  c4  d4
5  a5  b5  c5  d5

In [3]:
# 데이터 프레임 연결
result1 = pd.concat([df1, df2])
result1

    a   b   c    d
0  a0  b0  c0  NaN
1  a1  b1  c1  NaN
2  a2  b2  c2  NaN
3  a3  b3  c3  NaN
2  a2  b2  c2   d2
3  a3  b3  c3   d3
4  a4  b4  c4   d4
5  a5  b5  c5   d5

In [4]:
# join='inner' => 교집합 옵션
result2_in = pd.concat([df1,df2], axis=0, join='inner')
result2_in

    a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2
3  a3  b3  c3
2  a2  b2  c2
3  a3  b3  c3
4  a4  b4  c4
5  a5  b5  c5

In [5]:
# 인덱스 재정렬
result2 = pd.concat([df1,df2], ignore_index=True)
result2

    a   b   c    d
0  a0  b0  c0  NaN
1  a1  b1  c1  NaN
2  a2  b2  c2  NaN
3  a3  b3  c3  NaN
4  a2  b2  c2   d2
5  a3  b3  c3   d3
6  a4  b4  c4   d4
7  a5  b5  c5   d5

In [6]:
# axis = 1 => 좌우 열방향 연결
result3 = pd.concat([df1,df2], axis=1)
result3

     a    b    c    a    b    c    d
0   a0   b0   c0  NaN  NaN  NaN  NaN
1   a1   b1   c1  NaN  NaN  NaN  NaN
2   a2   b2   c2   a2   b2   c2   d2
3   a3   b3   c3   a3   b3   c3   d3
4  NaN  NaN  NaN   a4   b4   c4   d4
5  NaN  NaN  NaN   a5   b5   c5   d5

In [7]:
# 교집합
result3_in = pd.concat([df1,df2], axis=1, join='inner')
result3_in

    a   b   c   a   b   c   d
2  a2  b2  c2  a2  b2  c2  d2
3  a3  b3  c3  a3  b3  c3  d3

In [ ]:
# 시리즈 연결
sr1 = pd.Series(['e0','e1','e2','e3'], name='e')
sr2 = pd.Series(['f0','f1','f2'], name='f', index=[3,4,5])
sr3 = pd.Series(['g0','g1','g2','g3'], name='g')
sr4 = pd.Series(['a6','b6','c6','d6'], index=['a','b','c','d'])

# df1/sr1 열방향 결합 = 새로운 열 추가
result4 = pd.concat([df1, sr1], axis=1)
result4

    a   b   c   e
0  a0  b0  c0  e0
1  a1  b1  c1  e1
2  a2  b2  c2  e2
3  a3  b3  c3  e3

In [ ]:
# df2/sr2열방향 결합 = 새로운 열 추가
result5 = pd.concat([df2, sr2], axis=1)
# 일치하지 않는 행에 결측치 생성됨
result5

    a   b   c   d    f
2  a2  b2  c2  d2  NaN
3  a3  b3  c3  d3   f0
4  a4  b4  c4  d4   f1
5  a5  b5  c5  d5   f2

In [ ]:
# .to_frame() => sr4를 데이터프레임으로 변환
# .T => 행과 열을 전치시키는 명령어
# sr4
sr4.to_frame().T

    a   b   c   d
0  a6  b6  c6  d6

In [ ]:
# df2 와 sr4를 위 아래 열 방향 연결
# .to_frame().T => sr4를 데이터프레임으로 변환 후 행과 열을 전치시키는 명령어
result6 = pd.concat([df2, sr4.to_frame().T], ignore_index=True)
result6

    a   b   c   d
0  a2  b2  c2  d2
1  a3  b3  c3  d3
2  a4  b4  c4  d4
3  a5  b5  c5  d5
4  a6  b6  c6  d6

In [ ]:
# 시리즈 + 시리즈 좌우 열 방향 연결
result7 = pd.concat([sr1,sr3], axis=1)
result7

    e   g
0  e0  g0
1  e1  g1
2  e2  g2
3  e3  g3

In [ ]:
# 시리즈 + 시리즈 행 연결
result8 = pd.concat([sr1, sr3])
result8

0    e0
1    e1
2    e2
3    e3
0    g0
1    g1
2    g2
3    g3
dtype: object

### 병합
- SQL과 같은 관계형 데이터베이스와 유사한 조인 연산을 수행
- 어떤 기준에 의해 두 DataFrame을 병합(합치)하는 것
- 기준이 되는 열이나 인덱스를 Key라함
- Series는 보통 DataFrame에 붙이는 용도
- 기준 키 찾는 순서
    → 같은 이름의 컬럼 존재 -> 해당 컬럼을 on으로 설정
    → 같은 이름의 컬럼 없으며 -> valueError 발생

``` py
pandas.merge(left, # 왼쪽 DataFrame/Series
             right, # 오른쪽 DataFrame/Series
             how=‘inner’, # 병합 방식
             on=None, # None : 공통 열 키로 설정
             left_on, # 왼쪽에서 사용할 열 이름
             right_on, # 오른쪽에서 사용할 열 이름
             left_index=False, # 결합 기준으로 왼쪽 인덱스 사용 여부
             right_index=False, # 결합 기준으로 오른쪽 인덱스 사용 여부
             sort=False, # 결과를 키 기준으로 정렬 여부
             suffixes=('_x', '_y'), # 중복 열 이름 뒤에 붙일 접미사 
             )
```