### [데이터 전처리를 위한 인코딩]
* 컬럼 중 문자형/범주형인 데이터를 숫자로 변환하는 작업
* 컴퓨터가 분석 및 학습을 하기 쉽도록 변환
* 종류
    * 정수 인코딩/ 정수 라벨링
    * 원-핫 인코딩

In [13]:
# 모듈 로딩
import pandas as pd # 데이터 분석용 패키지
import numpy as np  # 배열을 파이썬언어로 규현한 패키지
                    # 판타스에서 데이터 저장을 numpy 배열로 함
import sys
sys.path.append('../utils')
from utils import data_info

In [14]:
## 데이터 준비 및 DF 인스턴스 생성
DATA_FILE = '../DATA/iris.csv'

# 첫번째 줄 : 컬럼명 ok, 구분자 : 쉼표/콤마 ok
iris_df = pd.read_csv(DATA_FILE)

In [15]:
data_info(iris_df)

요약정보(.info())
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

상위 정보
   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
...
     sepal.length  sepal.width  petal.length  petal.width    variety
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

수치 컬럼별 정보(.describe())
       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [16]:
iris_df.head(2)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa

- 방법1) variety 컬럼 object ==> 숫자/정수 라벨 인코딩

In [23]:
# 품종명에 설정될 값 매핑
irisDF_map = {
"Setosa": 0,
"Versicolor": 1,
"Virginica": 2}

## 결측값 NaN에는 함수 적용하여 NaN. 결과를 새로운 컬럼 추가
iris_df["variety_label"] = iris_df['variety'].map(irisDF_map)

iris_df[1::50]

,sepal.length,sepal.width,petal.length,petal.width,variety,variety_label
1,4.9,3.0,1.4,0.2,Setosa,0
51,6.4,3.2,4.5,1.5,Versicolor,1
101,5.8,2.7,5.1,1.9,Virginica,2

- 방법2) 특정 값만 1로 설정하는 인코딩 : 원-핫 인코딩

In [28]:
iris_df2 = pd.get_dummies(iris_df, columns=["variety"], dtype=int)
iris_df2[1::50]

,sepal.length,sepal.width,petal.length,petal.width,variety_label,variety_Setosa,variety_Versicolor,variety_Virginica
1,4.9,3.0,1.4,0.2,0,1,0,0
51,6.4,3.2,4.5,1.5,1,0,1,0
101,5.8,2.7,5.1,1.9,2,0,0,1